import os

env = Environment(ENV=os.environ)

library_path = env['ENV']['CODE_LIBRARY_PATH']
cppdefines = ['UNIX_TIME_TYPE=uint64_t', 'TEST']
cppflags = ['-Wall', '-Wextra']

for target in COMMAND_LINE_TARGETS:

	cpppath = ["#../", library_path, "#./" + target]
	conscript = target+"/SConscript"
	test_objects = SConscript(conscript, exports='cppflags cpppath cppdefines library_path')

	program = env.Program(test_objects, LIBS=['cppunit'], CC='g++')
	target_cmd = "./{0}/{0}.test".format(target)
	test_alias = env.Alias(target, [program], program[0].path)
	env.AlwaysBuild(test_alias)
