Import('cppflags', 'cpppath', 'cppdefines', 'library_path')
objects = [
	Object('alarm.test.cpp', CPPFLAGS=cppflags, CPPPATH=cpppath, CPPDEFINES=cppdefines),
	Object('../../alarm.cpp', CPPFLAGS=cppflags, CPPPATH=cpppath, CPPDEFINES=cppdefines),
	Object(library_path+'/Utility/util_time.c', CPPFLAGS=cppflags, CPPPATH=cpppath, CPPDEFINES=cppdefines, CC='g++'),
	Object(library_path+'/Utility/util_simple_compare.c', CPPFLAGS=cppflags, CPPPATH=cpppath, CPPDEFINES=cppdefines, CC='g++')
]
Return('objects')
